development:
  adapter: postgresql
  host: localhost
  database: spending_money_dev

test:
  adapter: postgresql
  host: localhost
  database: spending_money_test

production:
  adapter: postgresql
  host: localhost
  database: spending_money
